---
title: "RGTM_Output"
author: "Sicheng Hao"
date: "11/29/2020"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(data.table)
library(survival)
library(DiagrammeR)
library(ggridges)
library(tidyr)
```
## Find out where is the bias

```{r}
rd.11<-fread("v3-1.csv")
#rd.10<-fread("rd10.csv")
#e1 biased
#e2 gound truth
#e3 adjusted
# rd.10$cutoff<-as.factor(rd.10$cutoff)
# levels(rd.10$cutoff)[5]<-"No cutoff"
# rd.10$cutoff.n<-as.numeric(rd.10$cutoff)

rd.11$cutoff<-as.factor(rd.11$cutoff)
levels(rd.11$cutoff)[5]<-"No cutoff"
rd.11$cutoff.n<-as.numeric(rd.11$cutoff)
```



#### Without Treatment Heterogeinity 

```{r}
data<-rd.11%>%
  transmute(cutoff,interaction = e1.beta1,multiple.followup = e2.beta1, adjusted = e3.beta1)%>%
  gather("method","beta1",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = beta1, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Treatment on Mediator")+
  ggtitle("Beta1")
```



### Mediator to Outcome (theta2 and theta3)


```{r}
#theta2
data<-rd.11%>%
  transmute(cutoff,interaction = e1.theta2,multiple.followup = e2.theta2, adjusted = e3.theta2)%>%
  gather("method","theta2",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = theta2, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("theta2")
```

```{r}
### theta3
data<-rd.11%>%
  transmute(cutoff,interaction = e1.theta3,multiple.followup = e2.theta3, adjusted = e3.theta3)%>%
  gather("method","theta3",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = theta3, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("theta3")
```



### Direct Effect(theta1)

```{r}

data<-rd.11%>%
  transmute(cutoff,interaction = e1.theta1,multiple.followup = e2.theta1, adjusted = e3.theta1)%>%
  gather("method","theta1",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = theta1, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("theta1")
```


### PM
```{r}
data<-rd.11%>%
  transmute(cutoff,interaction = e1.pm,multiple.followup = e2.pm, adjusted = e3.pm)%>%
  gather("method","Prop.Mediated",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = Prop.Mediated, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("PM")
```


### TE
```{r}
data<-rd.11%>%
  transmute(cutoff,interaction = e1.te,multiple.followup = e2.te, adjusted = e3.te)%>%
  gather("method","Prop.Mediated",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = Prop.Mediated, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("Total Effect from Package")
```


```{r}
data<-rd.11%>%
  transmute(cutoff,interaction = e1.te2,multiple.followup = e2.te2, adjusted = e3.te2)%>%
  gather("method","Prop.Mediated",-cutoff)

data$cutoff<-as.factor(data$cutoff)
levels(data$cutoff)[5]<-"No cutoff"
data$cutoff.n<-as.numeric(data$cutoff)

ggplot(data = data, aes(x = Prop.Mediated, y = cutoff.n, fill = cutoff)) +
   geom_density_ridges(alpha = 0.5)+
  facet_wrap(~method)+
  scale_y_discrete(limit = c(1:10),labels = data$cutoff)+
  coord_flip()+
  theme(legend.position = "bottom",axis.text.x = element_blank(),
        axis.title.x=element_blank())+
  xlab("Mediator on Outcome")+
  ggtitle("Total Effect from Regression")
```